### ISSUE TITLE
BSData Repo

### ISSUE THREAD

**Issue by GenWilhelm** [VisionHeavy/BSData_Shadow_War#3]
Hey man, thought I'd let you know that BSData have just opened up a Shadow War: Armageddon repo: https://github.com/BSData/wh40k-shadow-war-armageddon

If you want to have this data hosted by them on appspot alongside all the other major game systems, I would shoot them a message before they get started on their own version.

If you want to come chat with the 40k data guys feel free to join us on gitter: https://gitter.im/BSData/wh40k

**Comment by Crothas** [comment]
Got it merged with their Repo
